version: "3.7"
services:
  app:
    build: .
    ports:
      - "5000:80"
    volumes:
      - "./app:/app"
      - "./data:/data"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]